### ISSUE TITLE
'taxon' missing from documentation

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/S25#5]
In the explanation of how the biological entity concepts are defined https://github.com/nvs-vocabs/S25/ the table shows all the qualifiers, but is missing the biological-name/taxon. It might be 'obvious' but I think the documentation would be improved by adding that column on the left. 

Maybe also indicate which qualifiers are 'optional' (all of them?)

**Comment by gwemon** [comment]
Yes, all of them (apart from the name field) are optional. 
The fact there is no collection listed for the name field in the table you mention is because it does not exist. The name is only present in S25. I believe this to be a flaw which I would like to address soon. I think that the reason this was done at the time it was designed, was due to the feeling that we did not need to register taxon names in a separate vocabualry because we were cross-referencing to WoRMS or ITIS. However not all names can be cleanly mapped to a taxon and having a separate collection for it would help users search and retrieve biologicial entities and would help us manage the mappings to WoRMS and ITIS better.

**Comment by dr-shorthair** [comment]
I see in the text it says 
> S25 is made of the biological name (linked to authoritative taxonomic registries when a match is possible) combined with, when necessary, attributes that further describe the biological entity. 

But then the table below just shows

Stage | Sex | Size | Subcomponent | Shape | Colour | Subgroup
-- | -- | -- | -- | -- | -- | --
S11 | S10 | S09 | S12 | S14 | S15 | S13

I suggest it would reinforce the text explanation better if the table was 

Taxon | Stage | Sex | Size | Subcomponent | Shape | Colour | Subgroup
-- | -- | -- | -- | -- | -- | -- | --
_**name**_ | S11 | S10 | S09 | S12 | S14 | S15 | S13

**Comment by gwemon** [comment]
Ah I see what you mean now. Okay I will review this. Thank you.

**Comment by gwemon** [comment]
I have updated the readme text. Thank you.
